# Nama workflow (muncul di UI GitHub)
name: Belajar CI/CD Pipeline

# Kapan workflow ini dijalankan?
on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]

# Atau schedule: setiap hari jam 1 pagi
# on:
#   schedule:
#     - cron: "0 1 * * *"